
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class AudioConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, AudioConfig> _dataMap;
    private readonly System.Collections.Generic.List<AudioConfig> _dataList;
    
    public AudioConfigCategory(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AudioConfig>();
        _dataList = new System.Collections.Generic.List<AudioConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AudioConfig _v;
            _v = AudioConfig.DeserializeAudioConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AudioConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<AudioConfig> DataList => _dataList;

    public AudioConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AudioConfig Get(int key) => _dataMap[key];
    public AudioConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

