
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class GlobalConfigCategory
{

     private readonly GlobalConfig _data;

     public GlobalConfig Data => _data;

    public GlobalConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = GlobalConfig.DeserializeGlobalConfig(_buf);
    }


    /// <summary>
    /// 默认音量
    /// </summary>
     public float Volume => _data.Volume;
    /// <summary>
    /// 默认 Icon 位置
    /// </summary>
     public string DefaultIcon => _data.DefaultIcon;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

