
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MapConfig : Luban.BeanBase
{
    public MapConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MapName = _buf.ReadString();
        Location = _buf.ReadString();
        Music = _buf.ReadInt();
        Music_Ref = null;
        SpawnPos = ExternalTypeUtil.NewVector3(vec3.Deserializevec3(_buf));
    }

    public static MapConfig DeserializeMapConfig(ByteBuf _buf)
    {
        return new MapConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    public readonly string MapName;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Location;
    /// <summary>
    /// 背景音乐
    /// </summary>
    public readonly int Music;
    public AudioConfig Music_Ref;
    /// <summary>
    /// 默认位置
    /// </summary>
    public readonly UnityEngine.Vector3 SpawnPos;
   
    public const int __ID__ = -1840922722;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        Music_Ref = tables.AudioConfigCategory.GetOrDefault(Music);
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mapName:" + MapName + ","
        + "location:" + Location + ","
        + "music:" + Music + ","
        + "spawnPos:" + SpawnPos + ","
        + "}";
    }
}

}
