
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private AudioConfigCategory m_AudioConfigCategory;
    public AudioConfigCategory AudioConfigCategory 
    {
        get
        {
            if (m_AudioConfigCategory == null)
            {
                m_AudioConfigCategory = new AudioConfigCategory(defaultLoader("audioconfigcategory"));
                m_AudioConfigCategory.ResolveRef(this);
            }
            return m_AudioConfigCategory;
        }
        set
        {
            m_AudioConfigCategory = value;
            m_AudioConfigCategory.ResolveRef(this);
        }
    }
    private MapConfigCategory m_MapConfigCategory;
    public MapConfigCategory MapConfigCategory 
    {
        get
        {
            if (m_MapConfigCategory == null)
            {
                m_MapConfigCategory = new MapConfigCategory(defaultLoader("mapconfigcategory"));
                m_MapConfigCategory.ResolveRef(this);
            }
            return m_MapConfigCategory;
        }
        set
        {
            m_MapConfigCategory = value;
            m_MapConfigCategory.ResolveRef(this);
        }
    }
    private ItemConfigCategory m_ItemConfigCategory;
    public ItemConfigCategory ItemConfigCategory 
    {
        get
        {
            if (m_ItemConfigCategory == null)
            {
                m_ItemConfigCategory = new ItemConfigCategory(defaultLoader("itemconfigcategory"));
                m_ItemConfigCategory.ResolveRef(this);
            }
            return m_ItemConfigCategory;
        }
        set
        {
            m_ItemConfigCategory = value;
            m_ItemConfigCategory.ResolveRef(this);
        }
    }
    private GlobalConfigCategory m_GlobalConfigCategory;
    public GlobalConfigCategory GlobalConfigCategory 
    {
        get
        {
            if (m_GlobalConfigCategory == null)
            {
                m_GlobalConfigCategory = new GlobalConfigCategory(defaultLoader("globalconfigcategory"));
                m_GlobalConfigCategory.ResolveRef(this);
            }
            return m_GlobalConfigCategory;
        }
        set
        {
            m_GlobalConfigCategory = value;
            m_GlobalConfigCategory.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
