
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class AudioConfig : Luban.BeanBase
{
    public AudioConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Path = _buf.ReadString();
        Loop = _buf.ReadBool();
        Volume = _buf.ReadInt();
        InPool = _buf.ReadBool();
    }

    public static AudioConfig DeserializeAudioConfig(ByteBuf _buf)
    {
        return new AudioConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 音频类型(0声音音效、1UI音效、2背景音乐、3人声神效、4最大声效)
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 音量(0-100)
    /// </summary>
    public readonly int Volume;
    /// <summary>
    /// 池化(对于贯穿游戏流程较长的音频需要存到资源池)
    /// </summary>
    public readonly bool InPool;
   
    public const int __ID__ = 1647377048;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "path:" + Path + ","
        + "loop:" + Loop + ","
        + "volume:" + Volume + ","
        + "inPool:" + InPool + ","
        + "}";
    }
}

}
