
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(ByteBuf _buf) 
    {
        Volume = _buf.ReadFloat();
        DefaultIcon = _buf.ReadString();
    }

    public static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new GlobalConfig(_buf);
    }

    /// <summary>
    /// 默认音量
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 默认 Icon 位置
    /// </summary>
    public readonly string DefaultIcon;
   
    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "volume:" + Volume + ","
        + "defaultIcon:" + DefaultIcon + ","
        + "}";
    }
}

}
